### ISSUE TITLE
Unable to set the metric namespace using Open telemetry

### ISSUE THREAD

**Issue by Rithwik-Bojja** [Azure-Samples/azure-monitor-opentelemetry-python#3]
Using below code I am unable to set the metric namespace testname, because of which i opened a bug request.

    from opentelemetry import metrics
    from opentelemetry.sdk.metrics import Counter, MeterProvider
    from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
    from azure.monitor.opentelemetry.exporter import AzureMonitorMetricExporter
    
    rexporter = AzureMonitorMetricExporter.from_connection_string(
        "InstrumentationKey=a2dec36ee8df;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/"
    )
    rithreader = PeriodicExportingMetricReader(rexporter, export_interval_millis=5000)
    metrics.set_meter_provider(MeterProvider(metric_readers=[rithreader]))
    test = {
        "Name": "Rithwik"
    }
    rithmeter = metrics.get_meter("testname")
    rithcounter = rithmeter.create_counter("testcounter")
    rithcounter.add(1, test)

![enter image description here](https://i.imgur.com/9lKtLiu.png)

![enter image description here](https://i.imgur.com/tS7D2Ah.png)

Refer this [SO-Thread](https://stackoverflow.com/questions/77995914/opentelemetry-migration-from-opencencus-to-add-metrics-to-azure-insights) for more details.

**Comment by lzchen** [comment]
We are working on this issue and the tracking task is [here](https://github.com/Azure/azure-sdk-for-python/issues/33855). Please open up issues related to the Azure monitor OpenTelemetry SDKs [here](https://github.com/Azure/azure-sdk-for-python/issues/new/choose) next time.
